"""TVG1-TVG7: variant generation + blend tests — R-CALLIOPE-S-VARIANT-GEN."""
from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
sys.path.insert(0, str(Path(__file__).parent.parent))


# ── TVG1: --variants 1 baseline, no change vs current behavior ───────────────

def test_tvg1_variants_1_baseline(tmp_path):
    """--variants 1 (default) produces single output file without variant sections."""
    import generate_scene as gs

    mock_text = "Aurora raised her blade, moonlight catching the edge."

    with patch.object(gs, "dispatch_to_tier", return_value=mock_text), \
         patch.object(gs, "_publish_emotion"), \
         patch.object(gs, "route_scene", return_value={"tier": "cerebras_workhorse", "provider": "cerebras"}), \
         patch.object(gs, "load_config", return_value=gs.DEFAULT_CONFIG):
        out = tmp_path / "scene_001.md"
        sys.argv = [
            "generate_scene.py",
            "--prompt", "test",
            "--scene-type", "action_combat",
            "--variants", "1",
            "--output", str(out),
        ]
        with pytest.raises(SystemExit) as exc:
            gs.main()
        assert exc.value.code == 0
        assert out.exists()
        content = out.read_text()
        assert "[V1]" not in content
        assert "Aurora raised her blade" in content


# ── TVG2: --variants 3 produces 3 sections ───────────────────────────────────

def test_tvg2_variants_3_sections(tmp_path):
    """--variants 3 writes .variants.md with [V1], [V2], [V3] sections."""
    import generate_scene as gs

    call_count = 0
    def mock_dispatch(tier, prompt, *args, **kwargs):
        nonlocal call_count
        call_count += 1
        return f"Generated text for call {call_count}: {prompt[:30]}"

    with patch.object(gs, "dispatch_to_tier", side_effect=mock_dispatch), \
         patch.object(gs, "_publish_emotion"), \
         patch.object(gs, "route_scene", return_value={"tier": "cerebras_workhorse", "provider": "cerebras"}), \
         patch.object(gs, "load_config", return_value=gs.DEFAULT_CONFIG):
        out = tmp_path / "scene_v3.md"
        sys.argv = [
            "generate_scene.py",
            "--prompt", "Aurora test",
            "--scene-type", "action_combat",
            "--variants", "3",
            "--output", str(out),
        ]
        with pytest.raises(SystemExit) as exc:
            gs.main()
        assert exc.value.code == 0

    variants_path = out.with_suffix(".variants.md")
    assert variants_path.exists(), "variants.md not created"
    content = variants_path.read_text()
    assert "[V1]" in content
    assert "[V2]" in content
    assert "[V3]" in content
    assert call_count == 3


# ── TVG3: style hints are different per variant (prompt contains hint) ────────

def test_tvg3_variants_different_style_prompts(tmp_path):
    """Each variant prompt must contain a different style directive."""
    import generate_scene as gs

    prompts_seen = []
    def mock_dispatch(tier, prompt, *args, **kwargs):
        prompts_seen.append(prompt)
        return "variant text"

    variants = gs.generate_variants(
        prompt="Aurora draws her sword",
        scene_type="action_combat",
        n_variants=3,
        style_hints=None,
        config=gs.DEFAULT_CONFIG,
        gateway_url="http://localhost:8766",
        ollama_url="http://localhost:11434",
        tier_name="cerebras_workhorse",
    ) if False else None  # will be mocked below

    with patch.object(gs, "dispatch_to_tier", side_effect=mock_dispatch):
        variants = gs.generate_variants(
            prompt="Aurora draws her sword",
            scene_type="action_combat",
            n_variants=3,
            style_hints=None,
            config=gs.DEFAULT_CONFIG,
            gateway_url="http://localhost:8766",
            ollama_url="http://localhost:11434",
            tier_name="cerebras_workhorse",
        )

    assert len(variants) == 3
    assert len(prompts_seen) == 3
    # Each prompt must contain a different style directive
    directives = [p.split("\n")[0] for p in prompts_seen]
    assert len(set(directives)) == 3, f"Style directives not unique: {directives}"
    # Style names in output
    styles = [v["style"] for v in variants]
    assert "descriptive" in styles
    assert "action-fast" in styles
    assert "lyrical" in styles


# ── TVG4: blend_scene.py parses variants file correctly ──────────────────────

def test_tvg4_blend_parse_variants():
    """parse_variants_file extracts correct number of variants."""
    from blend_scene import parse_variants_file

    content = """# Scene Variants: action_combat
**Tier**: cerebras_workhorse | **Provider**: cerebras | **N**: 3
_Generated by Quill of Calliope — 2026-05-19T18:00:00_

---

## [V1] style=descriptive | latency=1200ms

Aurora stood in the doorway, silver light catching her armor.

## [V2] style=action-fast | latency=900ms

She moved. Blade up. Thrust.

## [V3] style=lyrical | latency=1100ms

Moonlight sang on the edge of the blade.

---
"""
    variants = parse_variants_file(content)
    assert len(variants) == 3
    assert 1 in variants
    assert 2 in variants
    assert 3 in variants
    assert variants[1]["style"] == "descriptive"
    assert variants[2]["style"] == "action-fast"
    assert variants[3]["style"] == "lyrical"
    assert "Aurora stood" in variants[1]["text"]


# ── TVG5: blend 1+2 includes both variant texts in prompt ────────────────────

def test_tvg5_blend_prompt_contains_both_variants():
    """blend_variants LLM prompt must contain text from both selected variants."""
    from blend_scene import blend_variants

    variants = {
        1: {"style": "descriptive", "text": "VARIANT_ONE_TEXT here."},
        2: {"style": "action-fast", "text": "VARIANT_TWO_TEXT here."},
    }
    prompts_seen = []
    def mock_post(url, json=None, timeout=None):
        prompts_seen.append(json.get("prompt", ""))
        resp = MagicMock()
        resp.status_code = 200
        resp.json.return_value = {"result": "blended output text"}
        resp.raise_for_status = lambda: None
        return resp

    import requests
    with patch.object(requests, "post", side_effect=mock_post):
        blended, _ = blend_variants(variants, [1, 2])

    assert prompts_seen, "No LLM call was made"
    prompt = prompts_seen[0]
    assert "VARIANT_ONE_TEXT" in prompt
    assert "VARIANT_TWO_TEXT" in prompt
    assert blended == "blended output text"


# ── TVG6: Flask /api/scene/variants returns 200 + variants list ───────────────

def test_tvg6_flask_variants_endpoint():
    """POST /api/scene/variants returns 200 and variants list."""
    from app.calliope_shell.server import create_app
    import generate_scene as gs

    def mock_gen(*args, **kwargs):
        return [
            {"style": "descriptive", "text": "V1 text", "latency_ms": 100},
            {"style": "action-fast", "text": "V2 text", "latency_ms": 90},
        ]

    with patch("generate_scene.generate_variants", side_effect=mock_gen), \
         patch("generate_scene._write_variants_file"), \
         patch("generate_scene.load_config", return_value=gs.DEFAULT_CONFIG), \
         patch("generate_scene.route_scene", return_value={"tier": "cerebras_workhorse", "provider": "cerebras"}):
        app, _ = create_app()
        app.config["TESTING"] = True
        with app.test_client() as client:
            r = client.post("/api/scene/variants", json={
                "prompt": "Aurora test",
                "scene_type": "action_combat",
                "n_variants": 2,
            })
    assert r.status_code == 200
    data = r.get_json()
    assert "variants" in data
    assert len(data["variants"]) == 2
    assert data["variants"][0]["style"] == "descriptive"


# ── TVG7: Flask /api/scene/blend returns 200 + blended text ──────────────────

def test_tvg7_flask_blend_endpoint(tmp_path):
    """POST /api/scene/blend returns 200 and blended_text."""
    # Create a real variants file
    variants_content = """# Scene Variants: action_combat
---

## [V1] style=descriptive | latency=100ms

Aurora raised her blade.

## [V2] style=action-fast | latency=90ms

She struck. Fast. Clean.

---
"""
    vfile = tmp_path / "test.variants.md"
    vfile.write_text(variants_content, encoding="utf-8")

    from app.calliope_shell.server import create_app
    import blend_scene as bs

    def mock_blend(variants, indices, hint=None, gateway_url=None):
        return "BLENDED OUTPUT TEXT", 300

    with patch.object(bs, "blend_variants", side_effect=mock_blend), \
         patch.object(bs, "write_blended_output"):
        app, _ = create_app()
        app.config["TESTING"] = True
        with app.test_client() as client:
            r = client.post("/api/scene/blend", json={
                "variants_file_path": str(vfile),
                "blend_indices": [1, 2],
            })
    assert r.status_code == 200
    data = r.get_json()
    assert "blended_text" in data
    assert data["blended_text"] == "BLENDED OUTPUT TEXT"
