"""TRP1-TRP6 — R-CALLIOPE-S-REFINE-PASS test suite."""

import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
sys.path.insert(0, str(Path(__file__).parent.parent))


# ─── helpers ────────────────────────────────────────────────────────────────

def _make_scene_file(tmp_path: Path, body: str = "She drew her blade. The enemy fell back.") -> Path:
    p = tmp_path / "scene.md"
    p.write_text(
        f"# Scene: action_combat\n"
        f"**Tier**: cerebras_workhorse | **Provider**: cerebras | **Latency**: 100ms | **Mode**: Generated\n"
        f"\n"
        f"{body}\n"
        f"\n"
        f"---\n"
        f"_Generated by Quill of Calliope M3 — 2026-05-19T00:00:00_\n",
        encoding="utf-8",
    )
    return p


# TRP1 — --refine --feedback produces shorter output (mocked dispatch)
def test_trp1_refine_produces_shorter_output(tmp_path):
    long_body = " ".join(["Aurora stood at the cliff edge."] * 20)
    scene_file = _make_scene_file(tmp_path, long_body)
    output_file = tmp_path / "refined.md"

    short_response = "She stood. She looked. Done."

    with (
        patch("generate_scene.dispatch_to_tier", return_value=short_response),
        patch("generate_scene.route_scene", return_value={"tier": "cerebras_workhorse", "provider": "cerebras"}),
        patch("generate_scene.load_config", return_value={}),
        patch("generate_scene._publish_emotion"),
    ):
        sys.argv = [
            "generate_scene.py",
            "--refine", str(scene_file),
            "--feedback", "accorcia e semplifica",
            "--output", str(output_file),
        ]
        with pytest.raises(SystemExit) as exc:
            import generate_scene as gs  # noqa: PLC0415
            gs.main()
        assert exc.value.code == 0

    refined = output_file.read_text(encoding="utf-8")
    assert short_response in refined
    assert len(refined) < len(scene_file.read_text(encoding="utf-8")) * 2


# TRP2 — --refine without --feedback → CLI error (exit != 0)
def test_trp2_refine_without_feedback_errors(tmp_path):
    scene_file = _make_scene_file(tmp_path)
    output_file = tmp_path / "out.md"
    sys.argv = [
        "generate_scene.py",
        "--refine", str(scene_file),
        "--output", str(output_file),
    ]
    with pytest.raises(SystemExit) as exc:
        import generate_scene as gs  # noqa: PLC0415
        # Reload to reset state
        import importlib  # noqa: PLC0415
        importlib.reload(gs)
        gs.main()
    assert exc.value.code != 0


# TRP3 — --auto-lint calls _auto_lint_loop post-refine (mocked)
def test_trp3_auto_lint_called(tmp_path):
    import generate_scene as gs  # noqa: PLC0415

    scene_file = _make_scene_file(tmp_path)
    output_file = tmp_path / "refined_lint.md"

    with (
        patch.object(gs, "dispatch_to_tier", return_value="Clean text."),
        patch.object(gs, "route_scene", return_value={"tier": "cerebras_workhorse", "provider": "cerebras"}),
        patch.object(gs, "load_config", return_value={}),
        patch.object(gs, "_publish_emotion"),
        patch.object(gs, "_auto_lint_loop", return_value="Clean text.") as mock_lint,
    ):
        sys.argv = [
            "generate_scene.py",
            "--refine", str(scene_file),
            "--feedback", "rimuovi clichés",
            "--auto-lint",
            "--output", str(output_file),
        ]
        with pytest.raises(SystemExit) as exc:
            gs.main()
        assert exc.value.code == 0
        mock_lint.assert_called_once()


# TRP4 — refine preserves emotion publish (mock mascot POST)
def test_trp4_refine_publishes_emotion(tmp_path):
    import generate_scene as gs  # noqa: PLC0415

    scene_file = _make_scene_file(tmp_path)
    output_file = tmp_path / "refined_em.md"

    with (
        patch.object(gs, "dispatch_to_tier", return_value="Aurora fought bravely."),
        patch.object(gs, "route_scene", return_value={"tier": "cerebras_workhorse", "provider": "cerebras"}),
        patch.object(gs, "load_config", return_value={}),
        patch.object(gs, "_publish_emotion") as mock_em,
    ):
        sys.argv = [
            "generate_scene.py",
            "--refine", str(scene_file),
            "--feedback", "aggiungi azione",
            "--emotion-test", "determined",
            "--output", str(output_file),
        ]
        with pytest.raises(SystemExit) as exc:
            gs.main()
        assert exc.value.code == 0
        mock_em.assert_called_once()
        call_args = mock_em.call_args[0]
        assert call_args[0] == "determined"


# TRP5 — Flask /api/scene/refine returns 200 + refined_text
def test_trp5_flask_refine_route_200():
    from app.calliope_shell.server import create_app  # noqa: PLC0415

    app, _ = create_app()
    app.config["TESTING"] = True

    with app.test_client() as client:
        with patch("requests.post") as mock_post:
            mock_resp = MagicMock()
            mock_resp.status_code = 200
            mock_resp.json.return_value = {"result": "Aurora moved swiftly."}
            mock_resp.raise_for_status = MagicMock()
            mock_post.return_value = mock_resp

            resp = client.post(
                "/api/scene/refine",
                json={
                    "scene_text": "Aurora stood and looked at the horizon.",
                    "feedback": "rendi più breve",
                    "auto_lint": False,
                },
                content_type="application/json",
            )

    assert resp.status_code == 200
    data = resp.get_json()
    assert "refined_text" in data
    assert data["refined_text"] == "Aurora moved swiftly."


# TRP6 — refine uses same scene_type routing as generate
def test_trp6_refine_uses_routing_config(tmp_path):
    import generate_scene as gs  # noqa: PLC0415

    scene_file = _make_scene_file(tmp_path)
    output_file = tmp_path / "routed.md"

    with (
        patch.object(gs, "dispatch_to_tier", return_value="Result text.") as mock_dispatch,
        patch.object(gs, "route_scene", return_value={"tier": "groq_tier", "provider": "groq"}) as mock_route,
        patch.object(gs, "load_config", return_value={"test": True}),
        patch.object(gs, "_publish_emotion"),
    ):
        sys.argv = [
            "generate_scene.py",
            "--refine", str(scene_file),
            "--feedback", "rendi più tense",
            "--scene-type", "action_combat",
            "--output", str(output_file),
        ]
        with pytest.raises(SystemExit) as exc:
            gs.main()
        assert exc.value.code == 0
        assert mock_route.called
        call_args = mock_route.call_args[0]
        assert call_args[0] == "action_combat"
        assert mock_dispatch.called
        assert "groq_tier" in mock_dispatch.call_args[0]
