#!/usr/bin/env python3
"""Blend N variants of a Calliope scene into a hybrid output.

Usage:
    python scripts/blend_scene.py <variants_file.md> --blend 1+2 --output blended.md
    python scripts/blend_scene.py <variants_file.md> --blend 1+3 --hint "take dialogue from V1, action from V3"

Corpus pattern (R-CALLIOPE-S-VARIANT-GEN): operator picks 2-3 variants then requests
"versione ibrida che unisca la 3 e la 2 (dalla 3: descrizioni ambiente; dalla 2: sottinteso)".
"""

import argparse
import logging
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).parent))

import requests  # noqa: E402


_GATEWAY_URL = "http://localhost:8766"
_BLEND_SYSTEM = (
    "You are a literary editor for a fantasy RP narrative. "
    "Your task is to blend two or more scene variants into a single coherent hybrid. "
    "Preserve the best elements from each variant as instructed. "
    "Output ONLY the blended scene text, no meta-commentary."
)


def parse_variants_file(content: str) -> Dict[int, Dict[str, str]]:
    """Parse a .variants.md file → {variant_number: {style, text}}."""
    pattern = re.compile(
        r"##\s+\[V(\d+)\]\s+style=([\w-]+)(?:\s+\|[^\n]*)?\n(.*?)(?=\n##\s+\[V\d+\]|\n---|\Z)",
        re.DOTALL,
    )
    variants: Dict[int, Dict[str, str]] = {}
    for m in pattern.finditer(content):
        num = int(m.group(1))
        style = m.group(2)
        text = m.group(3).strip()
        variants[num] = {"style": style, "text": text}
    return variants


def parse_blend_spec(blend_spec: str) -> List[int]:
    """Parse '1+2' or '1+2+3' → [1, 2, 3]."""
    parts = re.split(r"[+,\s]+", blend_spec.strip())
    return [int(p) for p in parts if p.isdigit()]


def blend_variants(
    variants: Dict[int, Dict[str, str]],
    indices: List[int],
    hint: Optional[str] = None,
    gateway_url: str = _GATEWAY_URL,
) -> Tuple[str, int]:
    """Call LLM to blend selected variants. Returns (blended_text, latency_ms)."""
    selected = [(i, variants[i]) for i in indices if i in variants]
    if not selected:
        raise ValueError(f"No valid variants found for indices {indices}")

    # Build blend prompt
    parts = []
    for i, v in selected:
        label = f"V{i} (style={v['style']})"
        parts.append(f"### {label}\n{v['text']}")

    variants_block = "\n\n".join(parts)
    blend_hint = hint or (
        "Blend the variants, taking environmental description from V1 "
        "and action/implication from V2, creating a single coherent scene."
    )

    prompt = (
        f"Blend the following scene variants into one cohesive scene.\n\n"
        f"{variants_block}\n\n"
        f"Blending instruction: {blend_hint}\n\n"
        "Write the blended scene as 2-3 paragraphs in third person."
    )

    import time  # noqa: PLC0415
    t0 = time.perf_counter()
    try:
        resp = requests.post(
            f"{gateway_url}/llm_ask",
            json={
                "provider": "groq",
                "model": "llama-3.3-70b-versatile",
                "prompt": prompt,
                "system": _BLEND_SYSTEM,
                "temperature": 0.6,
            },
            timeout=45,
        )
        resp.raise_for_status()
        data = resp.json()
        blended = data.get("result") or data.get("text") or data.get("content", "")
    except Exception as exc:
        logging.warning("blend LLM call failed: %s", exc)
        blended = "[blend failed — LLM call error]"
    latency_ms = round((time.perf_counter() - t0) * 1000)
    return blended, latency_ms


def write_blended_output(
    output_path: Path,
    blended_text: str,
    indices: List[int],
    hint: Optional[str],
    latency_ms: int,
    source_path: Path,
) -> None:
    from datetime import datetime  # noqa: PLC0415
    ts = datetime.now().isoformat(timespec="seconds")
    blend_label = "+".join(f"V{i}" for i in indices)
    content = (
        f"# Scene Blend: {blend_label}\n"
        f"**Source**: {source_path.name} | **Latency**: {latency_ms}ms\n"
        f"**Hint**: {hint or '(default)'}\n"
        f"_Generated by Quill of Calliope blend_scene — {ts}_\n\n---\n\n"
        f"{blended_text}\n\n---\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Blend scene variants into a hybrid")
    parser.add_argument("variants_file", type=Path, help="Path to .variants.md file")
    parser.add_argument(
        "--blend", required=True,
        help="Variant indices to blend, e.g. '1+2' or '1+3'",
    )
    parser.add_argument("--output", type=Path, help="Output .md path (default: <variants_file>.blend.md)")
    parser.add_argument("--hint", default=None, help="Blend instruction hint")
    parser.add_argument("--gateway-url", default=_GATEWAY_URL, help="LLM gateway base URL")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    if not args.variants_file.exists():
        print(f"Error: variants file not found: {args.variants_file}", file=sys.stderr)
        sys.exit(1)

    content = args.variants_file.read_text(encoding="utf-8")
    variants = parse_variants_file(content)
    if not variants:
        print("Error: no variants found in file (expected ## [V1] ... sections)", file=sys.stderr)
        sys.exit(1)

    indices = parse_blend_spec(args.blend)
    if not indices:
        print(f"Error: invalid --blend spec: {args.blend!r}", file=sys.stderr)
        sys.exit(1)

    output_path = args.output or args.variants_file.with_suffix(".blend.md")

    logging.info("Blending %s from %s", "+".join(f"V{i}" for i in indices), args.variants_file.name)
    blended, latency_ms = blend_variants(variants, indices, hint=args.hint, gateway_url=args.gateway_url)
    write_blended_output(output_path, blended, indices, args.hint, latency_ms, args.variants_file)

    logging.info("Blend written to %s (%dms)", output_path, latency_ms)
    print(f"✓ Blended output: {output_path}")


if __name__ == "__main__":
    main()
