#!/usr/bin/env python3
"""Generate a scene for Quill of Calliope RP engine.

Routes the generation request through the appropriate LLM tier based on content
policies, calls dispatch_to_tier() for real LLM output, and writes the result
as a Markdown file.
"""

import argparse
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict

# Insert scripts/ directory so `from route_scene import ...` resolves correctly
sys.path.insert(0, str(Path(__file__).parent))

from route_scene import (  # noqa: E402
    BlockedContentError,
    DEFAULT_CONFIG,
    dispatch_to_tier,
    load_config,
    route_scene,
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Quill of Calliope scene generator")
    parser.add_argument("--scene-type", default="action_combat", help="Scene type key")
    parser.add_argument("--prompt", required=True, help="Scene setup/context text")
    parser.add_argument(
        "--char-relevance",
        choices=["low", "high"],
        default="low",
        help="Character relevance level",
    )
    parser.add_argument(
        "--nsfw-score",
        default='{"nudity_explicit":0,"violence_gore":0,"non_consent":0,"minors_adjacent":0}',
        help="JSON string of NSFW risk scores",
    )
    parser.add_argument("--output", required=True, type=Path, help="Output .md file path")
    parser.add_argument(
        "--config", default="data/llm_routing_config.yaml", help="Routing config YAML path"
    )
    parser.add_argument(
        "--gateway-url", default="http://localhost:8765", help="LLM gateway base URL"
    )
    parser.add_argument(
        "--ollama-url", default="http://localhost:11434", help="Ollama base URL"
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    # Parse NSFW score
    try:
        nsfw_score: Dict = json.loads(args.nsfw_score)
    except json.JSONDecodeError as exc:
        print(f"Error: invalid JSON for --nsfw-score: {exc}", file=sys.stderr)
        sys.exit(1)

    # Load routing config with fallback to DEFAULT_CONFIG
    try:
        config = load_config(args.config)
    except Exception as exc:  # noqa: BLE001
        logging.warning("Config load failed (%s) — using DEFAULT_CONFIG", exc)
        config = DEFAULT_CONFIG

    # Route scene
    try:
        decision = route_scene(args.scene_type, nsfw_score, args.char_relevance, config)
    except BlockedContentError as exc:
        print(f"BLOCKED: {exc}", file=sys.stderr)
        sys.exit(2)
    except Exception as exc:  # noqa: BLE001
        print(f"Error during routing: {exc}", file=sys.stderr)
        sys.exit(1)

    tier_name: str = decision["tier"]
    provider: str = decision["provider"]

    # Build full LLM prompt
    full_prompt = (
        f"Write a {args.scene_type} scene for a fantasy RP server.\n\n"
        f"{args.prompt}\n\n"
        "Write 2-3 paragraphs in third person."
    )

    # Dispatch to LLM tier (with timing)
    t0 = time.perf_counter()
    try:
        scene_text = dispatch_to_tier(
            tier_name,
            full_prompt,
            config,
            args.gateway_url,
            args.ollama_url,
        )
    except Exception as exc:  # noqa: BLE001
        logging.warning("dispatch_to_tier failed (%s) — using placeholder", exc)
        scene_text = f"[generation failed — tier {tier_name}]"
    latency_ms = round((time.perf_counter() - t0) * 1000)

    logging.info("Tier %s selected — latency: %dms", tier_name, latency_ms)

    # Write Markdown output
    timestamp = datetime.now().isoformat(timespec="seconds")
    output_content = (
        f"# Scene: {args.scene_type}\n"
        f"**Tier**: {tier_name} | **Provider**: {provider} | **Latency**: {latency_ms}ms\n"
        f"\n"
        f"{scene_text}\n"
        f"\n"
        f"---\n"
        f"_Generated by Quill of Calliope M3 — {timestamp}_\n"
    )

    try:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output_content, encoding="utf-8")
    except Exception as exc:  # noqa: BLE001
        print(f"Error writing output file {args.output}: {exc}", file=sys.stderr)
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
