"""Unit test per scripts/generate_scene.py — _sanitize_user_prompt e _build_variant_prompt."""
from __future__ import annotations

from scripts.generate_scene import (
    _PROMPT_INJECTION_GUARD,
    _STYLE_DIRECTIVES,
    _build_variant_prompt,
    _sanitize_user_prompt,
)


def test_sanitize_empty():
    assert _sanitize_user_prompt("") == ""


def test_sanitize_truncation():
    long_text = "a" * 5000
    result = _sanitize_user_prompt(long_text)
    assert len(result) == 4000


def test_sanitize_injection_ignore_previous():
    assert _sanitize_user_prompt("IGNORE PREVIOUS") == "[IGNORE PREVIOUS]"


def test_sanitize_injection_system():
    assert _sanitize_user_prompt("SYSTEM:") == "[SYSTEM:]"


def test_sanitize_injection_assistant():
    assert _sanitize_user_prompt("ASSISTANT:") == "[ASSISTANT:]"


def test_sanitize_injection_user():
    assert _sanitize_user_prompt("USER:") == "[USER:]"


def test_sanitize_injection_instructions_word_boundary():
    # \b prima di ### richiede un word-char precedente (es. lettera)
    assert _sanitize_user_prompt("a### Instructions") == "a[### Instructions]"


# ─────────────────────────────────────────────────────────────────────────────
# Extended tests — generate_variants, _write_variants_file, _publish_emotion,
# _extract_scene_text, _check_free_ram_gb, _auto_lint_loop, main()
# ─────────────────────────────────────────────────────────────────────────────

import sys  # noqa: E402
from unittest.mock import MagicMock, patch  # noqa: E402

import pytest  # noqa: E402

from scripts.generate_scene import (  # noqa: E402
    _auto_lint_loop,
    _check_free_ram_gb,
    _extract_scene_text,
    _publish_emotion,
    _write_variants_file,
    generate_variants,
    main,
)

_GS = "scripts.generate_scene"


# ── _check_free_ram_gb ────────────────────────────────────────────────────────

def test_check_free_ram_gb_ok(monkeypatch):
    mock_result = MagicMock()
    mock_result.stdout = "Mem: 16384 8192 8192 0 4096 8000\n"
    monkeypatch.setattr("subprocess.run", MagicMock(return_value=mock_result))
    gb = _check_free_ram_gb()
    assert gb == pytest.approx(8000 / 1024, abs=0.1)


def test_check_free_ram_gb_exception_returns_999(monkeypatch):
    monkeypatch.setattr("subprocess.run", MagicMock(side_effect=OSError("no free")))
    assert _check_free_ram_gb() == 999.0


def test_check_free_ram_gb_no_mem_line(monkeypatch):
    mock_result = MagicMock()
    mock_result.stdout = "something else\n"
    monkeypatch.setattr("subprocess.run", MagicMock(return_value=mock_result))
    assert _check_free_ram_gb() == 999.0


# ── _publish_emotion ──────────────────────────────────────────────────────────

def test_publish_emotion_success():
    with patch(f"{_GS}.requests.post") as mock_post:
        _publish_emotion("happy", 0.8, "scene_01", "http://localhost:5000")
    mock_post.assert_called_once()
    assert "happy" in str(mock_post.call_args)


def test_publish_emotion_exception_silent():
    with patch(f"{_GS}.requests.post", side_effect=Exception("connection refused")):
        _publish_emotion("sad", 0.5, None, "http://localhost:5000")  # must not raise


# ── _extract_scene_text ───────────────────────────────────────────────────────

def test_extract_scene_text_strips_header_footer(tmp_path):
    f = tmp_path / "scene.md"
    f.write_text(
        "# Scene: action_combat\n"
        "**Tier**: local | **Provider**: ollama | **Latency**: 100ms | **Mode**: Generated\n"
        "\n"
        "The battlefield echoed with thunder.\n"
        "\n"
        "---\n"
        "_Generated by Quill of Calliope M3 — 2024-01-01T10:00:00_\n",
        encoding="utf-8",
    )
    result = _extract_scene_text(f)
    assert result == "The battlefield echoed with thunder."


def test_extract_scene_text_no_footer_returns_all(tmp_path):
    f = tmp_path / "scene.md"
    f.write_text("# Title\n**Tier**: x\n\nBody text.\n", encoding="utf-8")
    result = _extract_scene_text(f)
    assert "Body" in result


# ── _write_variants_file ──────────────────────────────────────────────────────

def test_write_variants_file_creates_md(tmp_path):
    variants = [
        {"style": "descriptive", "text": "Slow scene text.", "latency_ms": 120},
        {"style": "action-fast", "text": "Fast scene text.", "latency_ms": 80},
    ]
    out = tmp_path / "scene.variants.md"
    _write_variants_file(out, variants, "action_combat", "local", "ollama", "2024-01-01T10:00:00")
    content = out.read_text(encoding="utf-8")
    assert "Scene Variants: action_combat" in content
    assert "[V1]" in content
    assert "[V2]" in content
    assert "Slow scene text." in content


# ── generate_variants ─────────────────────────────────────────────────────────

def test_generate_variants_single(monkeypatch):
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch(f"{_GS}.dispatch_to_tier", return_value="Scene text"), \
         patch(f"{_GS}.filter_response", return_value=("Scene text", [])):
        variants = generate_variants(
            prompt="A battle begins.",
            scene_type="action_combat",
            n_variants=1,
            style_hints=None,
            config={},
            gateway_url="http://gw",
            ollama_url="http://ollama",
            tier_name="local",
        )
    assert len(variants) == 1
    assert variants[0]["text"] == "Scene text"
    assert variants[0]["style"] == "descriptive"


def test_generate_variants_dispatch_failure(monkeypatch):
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch(f"{_GS}.dispatch_to_tier", side_effect=RuntimeError("conn")), \
         patch(f"{_GS}.filter_response", return_value=("[variant 1 generation failed]", [])):
        variants = generate_variants("p", "dialogue", 1, None, {}, "gw", "ol", "local")
    assert "generation failed" in variants[0]["text"]


def test_generate_variants_custom_style_hints(monkeypatch):
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch(f"{_GS}.dispatch_to_tier", return_value="X"), \
         patch(f"{_GS}.filter_response", return_value=("X", [])):
        variants = generate_variants("p", "dialogue", 2, ["lyrical", "action-fast"], {}, "gw", "ol", "local")
    assert variants[0]["style"] == "lyrical"
    assert variants[1]["style"] == "action-fast"


def test_generate_variants_low_ram_logs_warning(monkeypatch, caplog):
    import logging
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=2.0))
    with patch(f"{_GS}.dispatch_to_tier", return_value="X"), \
         patch(f"{_GS}.filter_response", return_value=("X", [])), \
         caplog.at_level(logging.WARNING, logger="root"):
        generate_variants("p", "mystery", 1, None, {}, "gw", "ol", "local")
    assert any("RAM" in r.message for r in caplog.records)


# ── _auto_lint_loop ───────────────────────────────────────────────────────────

def test_auto_lint_loop_no_high_cliches(monkeypatch):
    mock_report = MagicMock()
    mock_report.findings = []  # no HIGH clichés
    mock_style_coach = MagicMock()
    mock_style_coach.lint_scene_output = MagicMock(return_value=mock_report)
    with patch.dict(sys.modules, {"app.calliope_shell.style_coach": mock_style_coach}):
        result = _auto_lint_loop("Clean text", "local", {}, "gw", "ol")
    assert result == "Clean text"


def test_auto_lint_loop_style_coach_import_error():
    with patch.dict(sys.modules, {"app.calliope_shell.style_coach": None}):
        result = _auto_lint_loop("Text", "local", {}, "gw", "ol")
    assert result == "Text"  # returns unchanged


def test_auto_lint_loop_refines_on_high(monkeypatch):
    high = MagicMock(severity="HIGH", pattern="golden eyes")
    none_findings = MagicMock()
    none_findings.findings = []
    one_finding = MagicMock()
    one_finding.findings = [high]
    mock_style_coach = MagicMock()
    mock_style_coach.lint_scene_output = MagicMock(side_effect=[one_finding, none_findings])
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch.dict(sys.modules, {"app.calliope_shell.style_coach": mock_style_coach}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="Refined text"), \
         patch(f"{_GS}.filter_response", return_value=("Refined text", [])):
        result = _auto_lint_loop("Original text", "local", {}, "gw", "ol")
    assert result == "Refined text"


# ── main() ────────────────────────────────────────────────────────────────────

def _base_argv(tmp_path, **extra):
    defaults = {
        "scene_type": "action_combat",
        "output": str(tmp_path / "out.md"),
    }
    defaults.update(extra)
    argv = ["prog", "--output", defaults["output"]]
    if "prompt" in defaults:
        argv += ["--prompt", defaults["prompt"]]
    if "scene_type" in defaults:
        argv += ["--scene-type", defaults["scene_type"]]
    if "refine" in defaults:
        argv += ["--refine", defaults["refine"], "--feedback", defaults.get("feedback", "fix it")]
    return argv


def _patch_route(tier="local", provider="ollama"):
    return patch(f"{_GS}.route_scene", return_value={"tier": tier, "provider": provider})


def test_main_generate_basic(monkeypatch, tmp_path):
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "A dark night.", "--output", str(tmp_path / "out.md")
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="Generated text."), \
         patch(f"{_GS}.filter_response", return_value=("Generated text.", [])), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0
    assert (tmp_path / "out.md").exists()


def test_main_refine_mode(monkeypatch, tmp_path):
    scene_file = tmp_path / "scene.md"
    scene_file.write_text(
        "# Scene: action_combat\n**Tier**: local | **Provider**: ollama | **Latency**: 0ms | **Mode**: Generated\n\nOld scene.\n\n---\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(sys, "argv", [
        "prog", "--refine", str(scene_file), "--feedback", "make it darker",
        "--output", str(tmp_path / "refined.md"),
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="Refined."), \
         patch(f"{_GS}.filter_response", return_value=("Refined.", [])), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0


def test_main_no_prompt_no_refine_exits(monkeypatch, tmp_path):
    monkeypatch.setattr(sys, "argv", ["prog", "--output", str(tmp_path / "out.md")])
    with pytest.raises(SystemExit) as exc:
        main()
    assert exc.value.code != 0


def test_main_invalid_nsfw_json_exits(monkeypatch, tmp_path):
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "text", "--output", str(tmp_path / "out.md"),
        "--nsfw-score", "{bad json",
    ])
    with pytest.raises(SystemExit) as exc:
        main()
    assert exc.value.code == 1


def test_main_blocked_content_exits(monkeypatch, tmp_path):
    from scripts.generate_scene import BlockedContentError
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--output", str(tmp_path / "out.md")
    ])
    with patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.route_scene", side_effect=BlockedContentError("blocked", "violence", 10)):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 2


def test_main_variants_path(monkeypatch, tmp_path):
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "p", "--variants", "2", "--output", str(tmp_path / "out.md")
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.generate_variants", return_value=[
             {"style": "descriptive", "text": "V1", "latency_ms": 100},
             {"style": "action-fast", "text": "V2", "latency_ms": 80},
         ]), \
         patch(f"{_GS}._write_variants_file"), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0


# ── generate_variants edge cases ─────────────────────────────────────────────

def test_generate_variants_more_than_hints_pool(monkeypatch):
    # n_variants > len(DEFAULT_STYLE_HINTS) and no custom hints → cycle (line 129)
    from scripts.generate_scene import DEFAULT_STYLE_HINTS
    n = len(DEFAULT_STYLE_HINTS) + 2
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch(f"{_GS}.dispatch_to_tier", return_value="X"), \
         patch(f"{_GS}.filter_response", return_value=("X", [])):
        variants = generate_variants("p", "action_combat", n, None, {}, "gw", "ol", "local")
    assert len(variants) == n


def test_generate_variants_fewer_hints_than_n(monkeypatch):
    # style_hints has 1 entry but n_variants=3 → pad (line 133)
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch(f"{_GS}.dispatch_to_tier", return_value="X"), \
         patch(f"{_GS}.filter_response", return_value=("X", [])):
        variants = generate_variants("p", "dialogue", 3, ["lyrical"], {}, "gw", "ol", "local")
    assert len(variants) == 3
    assert variants[1]["style"] == "lyrical"  # padded


def test_generate_variants_with_cliche_findings_logs(monkeypatch):
    # findings non vuoti → line 151 logged
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch(f"{_GS}.dispatch_to_tier", return_value="golden eyes everywhere"), \
         patch(f"{_GS}.filter_response", return_value=("cleaned", [{"pattern": "golden eyes", "severity": "HIGH"}])):
        variants = generate_variants("p", "dialogue", 1, None, {}, "gw", "ol", "local")
    assert variants[0]["text"] == "cleaned"


# ── main() additional edge cases ──────────────────────────────────────────────

def test_main_variants_plus_refine_exits(monkeypatch, tmp_path):
    # --variants incompatible with --refine → parser.error (line 335)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--variants", "2", "--refine", str(tmp_path / "scene.md"),
        "--feedback", "fix", "--output", str(tmp_path / "out.md"),
    ])
    with pytest.raises(SystemExit) as exc:
        main()
    assert exc.value.code != 0


def test_main_config_load_fails_uses_default(monkeypatch, tmp_path):
    # load_config raises → DEFAULT_CONFIG (lines 351-353)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--output", str(tmp_path / "out.md")
    ])
    with patch(f"{_GS}.load_config", side_effect=FileNotFoundError("no config")), \
         _patch_route(), \
         patch(f"{_GS}.dispatch_to_tier", return_value="T"), \
         patch(f"{_GS}.filter_response", return_value=("T", [])), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0


def test_main_routing_exception_exits(monkeypatch, tmp_path):
    # route_scene raises generic exception → exit 1 (lines 361-363)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--output", str(tmp_path / "out.md")
    ])
    with patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.route_scene", side_effect=RuntimeError("routing error")):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 1


def test_main_variants_capped_to_5(monkeypatch, tmp_path):
    # --variants 7 → capped to 5 with warning (line 372)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "p", "--variants", "7", "--output", str(tmp_path / "out.md")
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.generate_variants", return_value=[
             {"style": f"s{i}", "text": f"V{i}", "latency_ms": 100} for i in range(5)
         ]) as mock_gv, \
         patch(f"{_GS}._write_variants_file"), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit):
            main()
    assert mock_gv.call_args[1]["n_variants"] == 5


def test_main_refine_file_not_found_exits(monkeypatch, tmp_path):
    # --refine file missing → exit 1 (lines 419-420)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--refine", str(tmp_path / "missing.md"),
        "--feedback", "fix it", "--output", str(tmp_path / "out.md"),
    ])
    with _patch_route(), patch(f"{_GS}.load_config", return_value={}):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 1


def test_main_feedback_truncated(monkeypatch, tmp_path):
    # feedback > _MAX_FEEDBACK_LEN → truncated (lines 424-425)
    from scripts.generate_scene import _MAX_FEEDBACK_LEN
    scene_file = tmp_path / "scene.md"
    scene_file.write_text(
        "# Scene: action_combat\n**Tier**: local | **Provider**: ollama | **Latency**: 0ms | **Mode**: Generated\n\nOld scene.\n\n---\n",
        encoding="utf-8",
    )
    long_feedback = "x" * (_MAX_FEEDBACK_LEN + 100)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--refine", str(scene_file), "--feedback", long_feedback,
        "--output", str(tmp_path / "refined.md"),
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="R"), \
         patch(f"{_GS}.filter_response", return_value=("R", [])), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0


def test_main_dispatch_fail_uses_placeholder(monkeypatch, tmp_path):
    # dispatch_to_tier raises → placeholder text (lines 451-453)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--output", str(tmp_path / "out.md")
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", side_effect=RuntimeError("conn")), \
         patch(f"{_GS}.filter_response", return_value=("[generation failed — tier local]", [])), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0
    content = (tmp_path / "out.md").read_text(encoding="utf-8")
    assert "generation failed" in content


def test_main_cliche_findings_logged(monkeypatch, tmp_path):
    # filter_response returns findings → lines 461-463
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--output", str(tmp_path / "out.md")
    ])
    finding = {"severity": "HIGH", "pattern": "golden eyes", "count": 2, "action": "removed"}
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="text"), \
         patch(f"{_GS}.filter_response", return_value=("cleaned text", [finding])), \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0
    content = (tmp_path / "out.md").read_text(encoding="utf-8")
    assert "cleaned text" in content


def test_main_auto_lint_in_refine(monkeypatch, tmp_path):
    # --auto-lint + --refine → _auto_lint_loop called (line 469)
    scene_file = tmp_path / "scene.md"
    scene_file.write_text(
        "# Scene: action_combat\n**Tier**: local | **Provider**: ollama | **Latency**: 0ms | **Mode**: Generated\n\nOld.\n\n---\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(sys, "argv", [
        "prog", "--refine", str(scene_file), "--feedback", "fix",
        "--auto-lint", "--output", str(tmp_path / "out.md"),
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="R"), \
         patch(f"{_GS}.filter_response", return_value=("R", [])), \
         patch(f"{_GS}._auto_lint_loop", return_value="linted") as mock_al, \
         patch(f"{_GS}._publish_emotion"):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0
    mock_al.assert_called_once()


def test_main_output_write_fails_exits(monkeypatch, tmp_path):
    # output.write_text raises → exit 1 (lines 490-492)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--output", str(tmp_path / "out.md")
    ])
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="T"), \
         patch(f"{_GS}.filter_response", return_value=("T", [])), \
         patch(f"{_GS}._publish_emotion"), \
         patch("pathlib.Path.write_text", side_effect=PermissionError("no write")):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 1


def test_main_arc_append(monkeypatch, tmp_path):
    # --arc specified → append_scene path (lines 498-506)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--arc", "arc_01",
        "--output", str(tmp_path / "out.md"),
    ])
    mock_plot_arc = MagicMock()
    mock_plot_arc.get_arc = MagicMock(return_value=None)
    mock_plot_arc.append_scene = MagicMock(return_value={"scene_order": 3})
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="T"), \
         patch(f"{_GS}.filter_response", return_value=("T", [])), \
         patch(f"{_GS}._publish_emotion"), \
         patch.dict(sys.modules, {"app.calliope_shell.plot_arc": mock_plot_arc}):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0


def test_main_arc_append_fail_non_fatal(monkeypatch, tmp_path):
    # arc append raises → non-fatal warning (lines 505-506)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--arc", "arc_01",
        "--output", str(tmp_path / "out.md"),
    ])
    mock_plot_arc = MagicMock()
    mock_plot_arc.get_arc = MagicMock(return_value=None)
    mock_plot_arc.append_scene = MagicMock(side_effect=RuntimeError("db fail"))
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="T"), \
         patch(f"{_GS}.filter_response", return_value=("T", [])), \
         patch(f"{_GS}._publish_emotion"), \
         patch.dict(sys.modules, {"app.calliope_shell.plot_arc": mock_plot_arc}):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0  # non-fatal


# ── auto_lint_loop additional edge cases ──────────────────────────────────────

def test_auto_lint_loop_low_ram_stops(monkeypatch):
    # RAM check < threshold → break (lines 243-247)
    high = MagicMock(severity="HIGH", pattern="golden eyes")
    one_finding = MagicMock()
    one_finding.findings = [high]
    mock_style_coach = MagicMock()
    mock_style_coach.lint_scene_output = MagicMock(return_value=one_finding)
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=1.0))
    with patch.dict(sys.modules, {"app.calliope_shell.style_coach": mock_style_coach}):
        result = _auto_lint_loop("Original text", "local", {}, "gw", "ol")
    assert result == "Original text"  # unchanged (stopped by low RAM)


def test_auto_lint_loop_dispatch_fail_stops(monkeypatch):
    # dispatch_to_tier raises during auto-lint refine → break (lines 265-267)
    high = MagicMock(severity="HIGH", pattern="golden eyes")
    one_finding = MagicMock()
    one_finding.findings = [high]
    mock_style_coach = MagicMock()
    mock_style_coach.lint_scene_output = MagicMock(return_value=one_finding)
    monkeypatch.setattr(f"{_GS}._check_free_ram_gb", MagicMock(return_value=8.0))
    with patch.dict(sys.modules, {"app.calliope_shell.style_coach": mock_style_coach}), \
         patch(f"{_GS}.dispatch_to_tier", side_effect=RuntimeError("conn")), \
         patch(f"{_GS}.filter_response", return_value=("X", [])):
        result = _auto_lint_loop("Original text", "local", {}, "gw", "ol")
    assert result == "Original text"  # dispatch failed, returned original


def test_main_refine_without_feedback_exits(monkeypatch, tmp_path):
    # --refine without --feedback → parser.error (line 335)
    scene_file = tmp_path / "scene.md"
    scene_file.write_text("# Scene\n**Tier**: x\n\nBody.\n\n---\n", encoding="utf-8")
    monkeypatch.setattr(sys, "argv", [
        "prog", "--refine", str(scene_file), "--output", str(tmp_path / "out.md"),
    ])
    with pytest.raises(SystemExit) as exc:
        main()
    assert exc.value.code != 0


def test_main_arc_context_injected(monkeypatch, tmp_path):
    # arc_data truthy → arc context built (lines 399-410)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--arc", "arc_01",
        "--output", str(tmp_path / "out.md"),
    ])
    arc_data = {
        "title": "The Great Arc",
        "summary": "Heroes rise.",
        "chars": ["Aurora", "Philip"],
        "open_threads": [{"thread": "find the key"}, {"thread": "escape the dungeon"}],
    }
    mock_plot_arc = MagicMock()
    mock_plot_arc.get_arc = MagicMock(return_value=arc_data)
    mock_plot_arc.append_scene = MagicMock(return_value={"scene_order": 5})
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="T") as mock_dispatch, \
         patch(f"{_GS}.filter_response", return_value=("T", [])), \
         patch(f"{_GS}._publish_emotion"), \
         patch.dict(sys.modules, {"app.calliope_shell.plot_arc": mock_plot_arc}):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0
    prompt_used = mock_dispatch.call_args[0][1]
    assert "The Great Arc" in prompt_used


def test_main_arc_context_fetch_exception(monkeypatch, tmp_path):
    # arc fetch raises → non-fatal warning, continues (lines 413-414)
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--arc", "arc_01",
        "--output", str(tmp_path / "out.md"),
    ])
    mock_plot_arc = MagicMock()
    mock_plot_arc.get_arc = MagicMock(side_effect=RuntimeError("db error"))
    mock_plot_arc.append_scene = MagicMock(return_value=None)
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="T"), \
         patch(f"{_GS}.filter_response", return_value=("T", [])), \
         patch(f"{_GS}._publish_emotion"), \
         patch.dict(sys.modules, {"app.calliope_shell.plot_arc": mock_plot_arc}):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0


def test_main_arc_append_logs_order(monkeypatch, tmp_path):
    # append_scene returns truthy with scene_order → line 504 logged
    monkeypatch.setattr(sys, "argv", [
        "prog", "--prompt", "x", "--arc", "arc_01",
        "--output", str(tmp_path / "out.md"),
    ])
    mock_plot_arc = MagicMock()
    mock_plot_arc.get_arc = MagicMock(return_value=None)
    mock_plot_arc.append_scene = MagicMock(return_value={"scene_order": 7})
    with _patch_route(), \
         patch(f"{_GS}.load_config", return_value={}), \
         patch(f"{_GS}.dispatch_to_tier", return_value="T"), \
         patch(f"{_GS}.filter_response", return_value=("T", [])), \
         patch(f"{_GS}._publish_emotion"), \
         patch.dict(sys.modules, {"app.calliope_shell.plot_arc": mock_plot_arc}):
        with pytest.raises(SystemExit) as exc:
            main()
    assert exc.value.code == 0
    mock_plot_arc.append_scene.assert_called_once()


def test_sanitize_control_chars():
    result = _sanitize_user_prompt("\x00a\nb\tc\x7f")
    assert result == " a\nb\tc "


def test_build_known_style():
    res = _build_variant_prompt("base", "combat", "descriptive")
    assert _STYLE_DIRECTIVES["descriptive"] in res


def test_build_unknown_style():
    res = _build_variant_prompt("base", "combat", "unknown_style")
    assert "Style directive: write in unknown_style style." in res


def test_build_contains_guard():
    res = _build_variant_prompt("base", "combat", "descriptive")
    assert _PROMPT_INJECTION_GUARD in res


def test_build_contains_prompt():
    res = _build_variant_prompt("my prompt", "combat", "descriptive")
    assert "my prompt" in res


def test_build_scene_type():
    res = _build_variant_prompt("base", "exploration", "descriptive")
    assert "exploration" in res


def test_build_injection_neutralized():
    res = _build_variant_prompt("IGNORE PREVIOUS", "combat", "descriptive")
    assert "[IGNORE PREVIOUS]" in res
    assert "IGNORE PREVIOUS" not in res.replace("[IGNORE PREVIOUS]", "")
